package com.processguard.models;

import java.time.Instant;
import java.util.Objects;

/**
 * Represents a single alert event generated by the AlertEngine or CustomRuleEngine.
 * Matches section 4.2 of the Software Design Document (SDD).
 */
public class AlertEvent {

    private final long id;
    private final ProcessInfo process;
    private final AlertType type;
    private final Severity severity;
    private final String message;
    private final Instant timestamp;
    private boolean acknowledged;

    /**
     * Constructs a new AlertEvent.
     *
     * @param id         Unique alert identifier (generated by HistoryStorage or AlertEngine)
     * @param process    The ProcessInfo that triggered this alert
     * @param type       Type of the alert
     * @param severity   Severity level
     * @param message    Human-readable alert message
     */
    public AlertEvent(long id, ProcessInfo process, AlertType type,
                      Severity severity, String message) {
        this.id = id;
        this.process = Objects.requireNonNull(process, "ProcessInfo cannot be null");
        this.type = Objects.requireNonNull(type, "AlertType cannot be null");
        this.severity = Objects.requireNonNull(severity, "Severity cannot be null");
        this.message = (message != null && !message.isBlank())
                ? message
                : type.name() + " detected for process " + process.getName();
        this.timestamp = Instant.now();
        this.acknowledged = false;
    }

    // -------------------------------------------------------------------------
    // Getters
    // -------------------------------------------------------------------------

    public long getId() {
        return id;
    }

    public ProcessInfo getProcess() {
        return process;
    }

    public AlertType getType() {
        return type;
    }

    public Severity getSeverity() {
        return severity;
    }

    public String getMessage() {
        return message;
    }

    public Instant getTimestamp() {
        return timestamp;
    }

    public boolean isAcknowledged() {
        return acknowledged;
    }

    // -------------------------------------------------------------------------
    // Setters (only acknowledged is mutable)
    // -------------------------------------------------------------------------

    public void setAcknowledged(boolean acknowledged) {
        this.acknowledged = acknowledged;
    }

    // -------------------------------------------------------------------------
    // Utility methods
    // -------------------------------------------------------------------------

    @Override
    public String toString() {
        return String.format("AlertEvent[id=%d, type=%s, severity=%s, process=%s, message=%s]",
                id, type, severity, process.getName(), message);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AlertEvent)) return false;
        AlertEvent that = (AlertEvent) o;
        return id == that.id;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}